### ISSUE TITLE
Add configuration file support

### ISSUE THREAD

**Issue by kousen** [kousen/google-slides-to-slidev#3]
## Description
Allow users to customize the converter behavior through a configuration file instead of modifying the Python code.

## Proposed Features
Configuration options should include:
- **Theme selection** (default: seriph)
- **Background image URL** or color
- **Image sizing** (max-width, max-height)
- **Font choices**
- **Transition effects**
- **Output directory structure**
- **File naming patterns**

## Implementation Ideas
1. Support multiple config formats:
   - `slidev-converter.yaml`
   - `slidev-converter.json`
   - `.slidevrc`

2. Example YAML config:
```yaml
theme: seriph
background: https://source.unsplash.com/1920x1080/?technology
images:
  max_width: 80%
  max_height: 400px
  center: true
fonts:
  sans: Inter
  mono: Fira Code
output:
  directory: ./presentations
  filename_pattern: "{title}-{date}"
```

3. Command line flag: `--config custom-config.yaml`

## Benefits
- No code changes needed for customization
- Share configurations across teams
- Per-project settings
- Version control friendly
